// This file was autogenerated by C:/Users/5/Sites/sia/../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../sia/js/sia/secrets/combinationalnumbers.js', ['sia.secrets.CombinationalSymbols'], ['goog.array', 'goog.asserts', 'goog.json', 'goog.structs.Set', 'sia.secrets.VirtualSymbol', 'sia.secrets.resolveSet']);
goog.addDependency('../../../sia/js/sia/secrets/virtualsymbols.js', ['sia.secrets.VirtualSymbol', 'sia.secrets.resolveSet'], ['goog.array', 'goog.asserts', 'goog.structs', 'goog.structs.Map']);
goog.addDependency('../../../sia/js/sia/sia.js', ['sia'], ['goog.dom', 'goog.events', 'goog.object', 'goog.ui.Component', 'sia.ui.NumericalKeypad']);
goog.addDependency('../../../sia/js/sia/ui/functionkey.js', ['sia.ui.FunctionKey', 'sia.ui.FunctionKeyRenderer'], ['goog.dom', 'goog.ui.Button', 'goog.ui.ButtonRenderer', 'goog.ui.registry']);
goog.addDependency('../../../sia/js/sia/ui/numerickey.js', ['sia.ui.NumericalKey', 'sia.ui.NumericalKeyRenderer'], ['goog.events.Event', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.events.KeyCodes', 'goog.functions', 'goog.ui.Button', 'goog.ui.ButtonRenderer', 'goog.ui.Component.EventType', 'goog.ui.registry']);
goog.addDependency('../../../sia/js/sia/ui/numerickeypad.js', ['sia.ui.NumericalKeypad', 'sia.ui.NumericalKeypadRenderer'], ['goog.dom', 'goog.dom.dataset', 'goog.structs', 'goog.ui.Component', 'goog.ui.Container', 'goog.ui.ContainerRenderer', 'goog.ui.registry', 'sia.secret.CombinationalSymbols', 'sia.ui.FunctionKey', 'sia.ui.NumericalKey']);
